### PR TITLE
Added links to tech. Changed names in ty section.

### PR DESCRIPTION
**Pull request by john-dulaney**
## Link to Ticket
Janitor

## Description of Proposed Changes

-  Added links to tech. Changed names in ty section.

## Steps to Test

Outline the steps to test

```sh
git fetch --all
git checkout JD-omg-windows

```
1. http server open the site
1. ensure the links work for each tech icon
1. das it man

## Impacted Areas in Application

List general components of the application that this PR will affect:

* tech.json, small change to main.js, small change to index.html

## Mentions @krnorris65 @Chewieez 

Tag users that need to review this code

### CODE REVIEW

**Comment by Chewieez** [comment]
Can you make one small change? Can you add `target="_blank"` to the `<a href>` tags for the technology links so that when you click them they open in a new window or tab?

**Comment by john-dulaney** [comment]
Yes i can. done!

**Comment by Chewieez** [comment]
Awesome 👍

**Comment by Gward2489** [comment]
man this green button is just sitting here john....

**Comment by Gward2489** [comment]
MERGE MERGE MERGE :1st_place_medal:

**Comment by john-dulaney** [comment]
yea i'll hit it tomorrow when im in a better state of mind

**Pull request merged**
